# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ORIR_Debug_Tool.ui',
# licensing of 'ORIR_Debug_Tool.ui' applies.
#
# Created: Wed Sep  9 15:19:19 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ORIR_Debug_Tool(object):
    def setupUi(self, ORIR_Debug_Tool):
        ORIR_Debug_Tool.setObjectName("ORIR_Debug_Tool")
        ORIR_Debug_Tool.resize(977, 733)
        self.load_pointcloud_data_btn = QtWidgets.QPushButton(ORIR_Debug_Tool)
        self.load_pointcloud_data_btn.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.load_pointcloud_data_btn.setObjectName("load_pointcloud_data_btn")
        self.set_edge_nums_btn = QtWidgets.QPushButton(ORIR_Debug_Tool)
        self.set_edge_nums_btn.setGeometry(QtCore.QRect(70, 170, 75, 23))
        self.set_edge_nums_btn.setObjectName("set_edge_nums_btn")
        self.label_7 = QtWidgets.QLabel(ORIR_Debug_Tool)
        self.label_7.setGeometry(QtCore.QRect(20, 80, 201, 16))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(ORIR_Debug_Tool)
        self.label_9.setGeometry(QtCore.QRect(30, 520, 91, 16))
        self.label_9.setObjectName("label_9")
        self.save_pic_btn = QtWidgets.QPushButton(ORIR_Debug_Tool)
        self.save_pic_btn.setGeometry(QtCore.QRect(270, 580, 75, 23))
        self.save_pic_btn.setObjectName("save_pic_btn")
        self.translation_pic_btn = QtWidgets.QPushButton(ORIR_Debug_Tool)
        self.translation_pic_btn.setGeometry(QtCore.QRect(30, 240, 75, 23))
        self.translation_pic_btn.setObjectName("translation_pic_btn")
        self.scale_pic_btn = QtWidgets.QPushButton(ORIR_Debug_Tool)
        self.scale_pic_btn.setGeometry(QtCore.QRect(120, 240, 75, 23))
        self.scale_pic_btn.setObjectName("scale_pic_btn")
        self.widget = QtWidgets.QWidget(ORIR_Debug_Tool)
        self.widget.setGeometry(QtCore.QRect(20, 110, 211, 42))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.up_nums_le = QtWidgets.QLineEdit(self.widget)
        self.up_nums_le.setObjectName("up_nums_le")
        self.verticalLayout.addWidget(self.up_nums_le)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.left_nums_le = QtWidgets.QLineEdit(self.widget)
        self.left_nums_le.setObjectName("left_nums_le")
        self.verticalLayout_2.addWidget(self.left_nums_le)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.bottom_nums_le = QtWidgets.QLineEdit(self.widget)
        self.bottom_nums_le.setObjectName("bottom_nums_le")
        self.verticalLayout_3.addWidget(self.bottom_nums_le)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.right_nums_le = QtWidgets.QLineEdit(self.widget)
        self.right_nums_le.setObjectName("right_nums_le")
        self.verticalLayout_4.addWidget(self.right_nums_le)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.widget1 = QtWidgets.QWidget(ORIR_Debug_Tool)
        self.widget1.setGeometry(QtCore.QRect(30, 560, 201, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.pic_width_le = QtWidgets.QLineEdit(self.widget1)
        self.pic_width_le.setObjectName("pic_width_le")
        self.horizontalLayout_2.addWidget(self.pic_width_le)
        self.widget2 = QtWidgets.QWidget(ORIR_Debug_Tool)
        self.widget2.setGeometry(QtCore.QRect(30, 590, 201, 22))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.pic_height_le = QtWidgets.QLineEdit(self.widget2)
        self.pic_height_le.setObjectName("pic_height_le")
        self.horizontalLayout_3.addWidget(self.pic_height_le)
        self.widget3 = QtWidgets.QWidget(ORIR_Debug_Tool)
        self.widget3.setGeometry(QtCore.QRect(20, 310, 258, 191))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.widget3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.output_te = QtWidgets.QTextEdit(self.widget3)
        self.output_te.setObjectName("output_te")
        self.verticalLayout_5.addWidget(self.output_te)

        self.retranslateUi(ORIR_Debug_Tool)
        QtCore.QMetaObject.connectSlotsByName(ORIR_Debug_Tool)

    def retranslateUi(self, ORIR_Debug_Tool):
        ORIR_Debug_Tool.setWindowTitle(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "Form", None, -1))
        self.load_pointcloud_data_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "加载点云图", None, -1))
        self.set_edge_nums_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "确定", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "边界点数量设置（默认均为200）", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "保存为图片：", None, -1))
        self.save_pic_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "保存", None, -1))
        self.translation_pic_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "平移", None, -1))
        self.scale_pic_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "缩放", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "  上", None, -1))
        self.up_nums_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "200", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "  左", None, -1))
        self.left_nums_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "200", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "  下", None, -1))
        self.bottom_nums_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "200", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "  右", None, -1))
        self.right_nums_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "200", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "图片的宽：", None, -1))
        self.pic_width_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "700", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "图片的高：", None, -1))
        self.pic_height_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "400", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("ORIR_Debug_Tool", "输出：", None, -1))

