# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ORIR_Debug_LogAnalysis_Page.ui',
# licensing of 'ORIR_Debug_LogAnalysis_Page.ui' applies.
#
# Created: Wed Jul 22 11:07:59 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ORIR_LogAnalysis_Page(object):
    def setupUi(self, ORIR_LogAnalysis_Page):
        ORIR_LogAnalysis_Page.setObjectName("ORIR_LogAnalysis_Page")
        ORIR_LogAnalysis_Page.resize(992, 725)
        self.gridLayout_3 = QtWidgets.QGridLayout(ORIR_LogAnalysis_Page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(ORIR_LogAnalysis_Page)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(74, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.get_local_ip_btn = QtWidgets.QPushButton(self.groupBox)
        self.get_local_ip_btn.setObjectName("get_local_ip_btn")
        self.gridLayout_2.addWidget(self.get_local_ip_btn, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ip_addr_le = QtWidgets.QLineEdit(self.groupBox)
        self.ip_addr_le.setObjectName("ip_addr_le")
        self.gridLayout.addWidget(self.ip_addr_le, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.tcp_port_le = QtWidgets.QLineEdit(self.groupBox)
        self.tcp_port_le.setObjectName("tcp_port_le")
        self.gridLayout.addWidget(self.tcp_port_le, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.udp_port_le = QtWidgets.QLineEdit(self.groupBox)
        self.udp_port_le.setObjectName("udp_port_le")
        self.gridLayout.addWidget(self.udp_port_le, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tcp_connect_btn = QtWidgets.QPushButton(self.groupBox)
        self.tcp_connect_btn.setObjectName("tcp_connect_btn")
        self.horizontalLayout_2.addWidget(self.tcp_connect_btn)
        self.udp_connect_btn = QtWidgets.QPushButton(self.groupBox)
        self.udp_connect_btn.setObjectName("udp_connect_btn")
        self.horizontalLayout_2.addWidget(self.udp_connect_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(ORIR_LogAnalysis_Page)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.net_type_cbb_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.net_type_cbb_2.setObjectName("net_type_cbb_2")
        self.net_type_cbb_2.addItem("")
        self.net_type_cbb_2.addItem("")
        self.net_type_cbb_2.addItem("")
        self.net_type_cbb_2.addItem("")
        self.gridLayout_4.addWidget(self.net_type_cbb_2, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.net_type_cbb_3 = QtWidgets.QComboBox(self.groupBox_3)
        self.net_type_cbb_3.setObjectName("net_type_cbb_3")
        self.net_type_cbb_3.addItem("")
        self.net_type_cbb_3.addItem("")
        self.net_type_cbb_3.addItem("")
        self.net_type_cbb_3.addItem("")
        self.gridLayout_4.addWidget(self.net_type_cbb_3, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 1)
        self.lifter_pos_le_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lifter_pos_le_2.setObjectName("lifter_pos_le_2")
        self.gridLayout_4.addWidget(self.lifter_pos_le_2, 2, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(ORIR_LogAnalysis_Page)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_14 = QtWidgets.QLabel(self.groupBox_11)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_11)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 2, 0, 1, 1)
        self.is_show_as_hex_cb = QtWidgets.QCheckBox(self.groupBox_11)
        self.is_show_as_hex_cb.setChecked(True)
        self.is_show_as_hex_cb.setObjectName("is_show_as_hex_cb")
        self.gridLayout_6.addWidget(self.is_show_as_hex_cb, 2, 2, 1, 1)
        self.clear_runinfo_btn = QtWidgets.QPushButton(self.groupBox_11)
        self.clear_runinfo_btn.setObjectName("clear_runinfo_btn")
        self.gridLayout_6.addWidget(self.clear_runinfo_btn, 2, 3, 1, 1)
        self.send_debug_msg_te = QtWidgets.QTextEdit(self.groupBox_11)
        self.send_debug_msg_te.setObjectName("send_debug_msg_te")
        self.gridLayout_6.addWidget(self.send_debug_msg_te, 3, 0, 1, 4)
        self.cycle_send_period_ms_le = QtWidgets.QLineEdit(self.groupBox_11)
        self.cycle_send_period_ms_le.setObjectName("cycle_send_period_ms_le")
        self.gridLayout_6.addWidget(self.cycle_send_period_ms_le, 4, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_11)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 4, 1, 1, 1)
        self.send_hex_data_cb = QtWidgets.QCheckBox(self.groupBox_11)
        self.send_hex_data_cb.setChecked(True)
        self.send_hex_data_cb.setObjectName("send_hex_data_cb")
        self.gridLayout_6.addWidget(self.send_hex_data_cb, 4, 2, 1, 1)
        self.send_debug_msg_btn = QtWidgets.QPushButton(self.groupBox_11)
        self.send_debug_msg_btn.setObjectName("send_debug_msg_btn")
        self.gridLayout_6.addWidget(self.send_debug_msg_btn, 4, 3, 1, 1)
        self.runinfo_te = QtWidgets.QTextEdit(self.groupBox_11)
        self.runinfo_te.setObjectName("runinfo_te")
        self.gridLayout_6.addWidget(self.runinfo_te, 1, 0, 1, 4)
        self.gridLayout_3.addWidget(self.groupBox_11, 0, 1, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 418, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 10)

        self.retranslateUi(ORIR_LogAnalysis_Page)
        QtCore.QMetaObject.connectSlotsByName(ORIR_LogAnalysis_Page)

    def retranslateUi(self, ORIR_LogAnalysis_Page):
        ORIR_LogAnalysis_Page.setWindowTitle(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "Form", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "设置", None, -1))
        self.get_local_ip_btn.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "获取本机IP", None, -1))
        self.ip_addr_le.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "192.168.1.30", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "  UDP端口", None, -1))
        self.tcp_port_le.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "8800", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "  IP地址", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "  TCP端口", None, -1))
        self.udp_port_le.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "7777", None, -1))
        self.tcp_connect_btn.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "TCP连接", None, -1))
        self.udp_connect_btn.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "UDP连接", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "筛选", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "等级", None, -1))
        self.net_type_cbb_2.setItemText(0, QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "TCP服务器", None, -1))
        self.net_type_cbb_2.setItemText(1, QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "TCP客户端", None, -1))
        self.net_type_cbb_2.setItemText(2, QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "UDP服务器", None, -1))
        self.net_type_cbb_2.setItemText(3, QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "UDP客户端", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "标签", None, -1))
        self.net_type_cbb_3.setItemText(0, QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "TCP服务器", None, -1))
        self.net_type_cbb_3.setItemText(1, QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "TCP客户端", None, -1))
        self.net_type_cbb_3.setItemText(2, QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "UDP服务器", None, -1))
        self.net_type_cbb_3.setItemText(3, QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "UDP客户端", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "关键字", None, -1))
        self.groupBox_11.setTitle(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "调试框", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "接收框", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "发送框", None, -1))
        self.is_show_as_hex_cb.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "十六进制显示", None, -1))
        self.clear_runinfo_btn.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "清除", None, -1))
        self.send_debug_msg_te.setHtml(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">12345</p></body></html>", None, -1))
        self.cycle_send_period_ms_le.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "0", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "ms", None, -1))
        self.send_hex_data_cb.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "十六进制发送", None, -1))
        self.send_debug_msg_btn.setText(QtWidgets.QApplication.translate("ORIR_LogAnalysis_Page", "发送", None, -1))

