# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ORIR_Debug_Page.ui',
# licensing of 'ORIR_Debug_Page.ui' applies.
#
# Created: Thu Aug 20 11:42:25 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ORIR_Debug_Page(object):
    def setupUi(self, ORIR_Debug_Page):
        ORIR_Debug_Page.setObjectName("ORIR_Debug_Page")
        ORIR_Debug_Page.resize(1182, 940)
        self.gridLayout_23 = QtWidgets.QGridLayout(ORIR_Debug_Page)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.groupBox_5 = QtWidgets.QGroupBox(ORIR_Debug_Page)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_13.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.statuslight_red_on_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.statuslight_red_on_btn.setObjectName("statuslight_red_on_btn")
        self.gridLayout_12.addWidget(self.statuslight_red_on_btn, 0, 0, 1, 1)
        self.statuslight_yellow_on_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.statuslight_yellow_on_btn.setObjectName("statuslight_yellow_on_btn")
        self.gridLayout_12.addWidget(self.statuslight_yellow_on_btn, 0, 1, 1, 1)
        self.statuslight_green_on_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.statuslight_green_on_btn.setObjectName("statuslight_green_on_btn")
        self.gridLayout_12.addWidget(self.statuslight_green_on_btn, 1, 0, 1, 1)
        self.statuslight_all_off_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.statuslight_all_off_btn.setObjectName("statuslight_all_off_btn")
        self.gridLayout_12.addWidget(self.statuslight_all_off_btn, 1, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_5, 7, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(ORIR_Debug_Page)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ptz_stop_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_stop_btn.setObjectName("ptz_stop_btn")
        self.gridLayout_3.addWidget(self.ptz_stop_btn, 1, 2, 1, 1)
        self.ptz_irup_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_irup_btn.setObjectName("ptz_irup_btn")
        self.gridLayout_3.addWidget(self.ptz_irup_btn, 0, 3, 1, 1)
        self.ptz_irdown_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_irdown_btn.setObjectName("ptz_irdown_btn")
        self.gridLayout_3.addWidget(self.ptz_irdown_btn, 2, 3, 1, 1)
        self.ptz_vldown_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_vldown_btn.setObjectName("ptz_vldown_btn")
        self.gridLayout_3.addWidget(self.ptz_vldown_btn, 2, 1, 1, 1)
        self.ptz_vlup_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_vlup_btn.setObjectName("ptz_vlup_btn")
        self.gridLayout_3.addWidget(self.ptz_vlup_btn, 0, 1, 1, 1)
        self.ptz_right_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_right_btn.setObjectName("ptz_right_btn")
        self.gridLayout_3.addWidget(self.ptz_right_btn, 1, 3, 1, 1)
        self.ptz_left_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_left_btn.setObjectName("ptz_left_btn")
        self.gridLayout_3.addWidget(self.ptz_left_btn, 1, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ptz_query_left_tilt_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_query_left_tilt_btn.setObjectName("ptz_query_left_tilt_btn")
        self.gridLayout_5.addWidget(self.ptz_query_left_tilt_btn, 3, 0, 1, 1)
        self.ptz_query_right_tilt_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_query_right_tilt_btn.setObjectName("ptz_query_right_tilt_btn")
        self.gridLayout_5.addWidget(self.ptz_query_right_tilt_btn, 5, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 0, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 3, 3, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 5, 3, 1, 1)
        self.ptz_set_left_tilt_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_set_left_tilt_btn.setObjectName("ptz_set_left_tilt_btn")
        self.gridLayout_5.addWidget(self.ptz_set_left_tilt_btn, 2, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 1, 3, 1, 1)
        self.ptz_cur_pan_le = QtWidgets.QLineEdit(self.groupBox_2)
        self.ptz_cur_pan_le.setObjectName("ptz_cur_pan_le")
        self.gridLayout_5.addWidget(self.ptz_cur_pan_le, 1, 1, 1, 2)
        self.ptz_query_bearing_pitching_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_query_bearing_pitching_btn.setObjectName("ptz_query_bearing_pitching_btn")
        self.gridLayout_5.addWidget(self.ptz_query_bearing_pitching_btn, 6, 3, 1, 1)
        self.ptz_query_bearing_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_query_bearing_btn.setObjectName("ptz_query_bearing_btn")
        self.gridLayout_5.addWidget(self.ptz_query_bearing_btn, 1, 0, 1, 1)
        self.ptz_set_bearing_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_set_bearing_btn.setObjectName("ptz_set_bearing_btn")
        self.gridLayout_5.addWidget(self.ptz_set_bearing_btn, 0, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 4, 3, 1, 1)
        self.ptz_set_right_tilt_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_set_right_tilt_btn.setObjectName("ptz_set_right_tilt_btn")
        self.gridLayout_5.addWidget(self.ptz_set_right_tilt_btn, 4, 0, 1, 1)
        self.ptz_bearing_le = QtWidgets.QLineEdit(self.groupBox_2)
        self.ptz_bearing_le.setObjectName("ptz_bearing_le")
        self.gridLayout_5.addWidget(self.ptz_bearing_le, 0, 1, 1, 2)
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 2, 3, 1, 1)
        self.ptz_set_bearing_pitching_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_set_bearing_pitching_btn.setObjectName("ptz_set_bearing_pitching_btn")
        self.gridLayout_5.addWidget(self.ptz_set_bearing_pitching_btn, 6, 0, 1, 1)
        self.ptz_set_left_tilt_le = QtWidgets.QLineEdit(self.groupBox_2)
        self.ptz_set_left_tilt_le.setObjectName("ptz_set_left_tilt_le")
        self.gridLayout_5.addWidget(self.ptz_set_left_tilt_le, 2, 1, 1, 2)
        self.ptz_cur_left_tilt_le = QtWidgets.QLineEdit(self.groupBox_2)
        self.ptz_cur_left_tilt_le.setObjectName("ptz_cur_left_tilt_le")
        self.gridLayout_5.addWidget(self.ptz_cur_left_tilt_le, 3, 1, 1, 2)
        self.ptz_set_right_tilt_le = QtWidgets.QLineEdit(self.groupBox_2)
        self.ptz_set_right_tilt_le.setObjectName("ptz_set_right_tilt_le")
        self.gridLayout_5.addWidget(self.ptz_set_right_tilt_le, 4, 1, 1, 2)
        self.ptz_cur_right_tilt_le_ = QtWidgets.QLineEdit(self.groupBox_2)
        self.ptz_cur_right_tilt_le_.setObjectName("ptz_cur_right_tilt_le_")
        self.gridLayout_5.addWidget(self.ptz_cur_right_tilt_le_, 5, 1, 1, 2)
        self.ptz_pitching_le_9 = QtWidgets.QLineEdit(self.groupBox_2)
        self.ptz_pitching_le_9.setObjectName("ptz_pitching_le_9")
        self.gridLayout_5.addWidget(self.ptz_pitching_le_9, 6, 1, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 2, 2, 1, 1)
        self.ptz_self_check_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_self_check_btn.setObjectName("ptz_self_check_btn")
        self.gridLayout_4.addWidget(self.ptz_self_check_btn, 0, 2, 1, 1)
        self.ptz_cur_velocity_le = QtWidgets.QLineEdit(self.groupBox_2)
        self.ptz_cur_velocity_le.setObjectName("ptz_cur_velocity_le")
        self.gridLayout_4.addWidget(self.ptz_cur_velocity_le, 2, 1, 1, 1)
        self.ptz_poweroff_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_poweroff_btn.setObjectName("ptz_poweroff_btn")
        self.gridLayout_4.addWidget(self.ptz_poweroff_btn, 3, 2, 1, 1)
        self.ptz_query_velocity_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_query_velocity_btn.setObjectName("ptz_query_velocity_btn")
        self.gridLayout_4.addWidget(self.ptz_query_velocity_btn, 2, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_4.addWidget(self.label_41, 1, 2, 1, 1)
        self.ptz_set_velocity_le = QtWidgets.QLineEdit(self.groupBox_2)
        self.ptz_set_velocity_le.setObjectName("ptz_set_velocity_le")
        self.gridLayout_4.addWidget(self.ptz_set_velocity_le, 1, 1, 1, 1)
        self.ptz_poweron_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_poweron_btn.setObjectName("ptz_poweron_btn")
        self.gridLayout_4.addWidget(self.ptz_poweron_btn, 3, 1, 1, 1)
        self.ptz_set_velocity_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_set_velocity_btn.setObjectName("ptz_set_velocity_btn")
        self.gridLayout_4.addWidget(self.ptz_set_velocity_btn, 1, 0, 1, 1)
        self.ptz_set_zero_position_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.ptz_set_zero_position_btn.setObjectName("ptz_set_zero_position_btn")
        self.gridLayout_4.addWidget(self.ptz_set_zero_position_btn, 3, 0, 1, 1)
        self.ptz_inplace_le = QtWidgets.QLineEdit(self.groupBox_2)
        self.ptz_inplace_le.setObjectName("ptz_inplace_le")
        self.gridLayout_4.addWidget(self.ptz_inplace_le, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_2, 0, 1, 4, 1)
        self.groupBox = QtWidgets.QGroupBox(ORIR_Debug_Page)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.net_type_cbb = QtWidgets.QComboBox(self.groupBox)
        self.net_type_cbb.setObjectName("net_type_cbb")
        self.net_type_cbb.addItem("")
        self.net_type_cbb.addItem("")
        self.net_type_cbb.addItem("")
        self.net_type_cbb.addItem("")
        self.gridLayout.addWidget(self.net_type_cbb, 0, 1, 1, 2)
        self.port_le = QtWidgets.QLineEdit(self.groupBox)
        self.port_le.setObjectName("port_le")
        self.gridLayout.addWidget(self.port_le, 2, 1, 1, 2)
        self.ip_addr_le = QtWidgets.QLineEdit(self.groupBox)
        self.ip_addr_le.setObjectName("ip_addr_le")
        self.gridLayout.addWidget(self.ip_addr_le, 1, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.net_connect_btn = QtWidgets.QPushButton(self.groupBox)
        self.net_connect_btn.setObjectName("net_connect_btn")
        self.gridLayout.addWidget(self.net_connect_btn, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.get_local_ip_btn = QtWidgets.QPushButton(self.groupBox)
        self.get_local_ip_btn.setObjectName("get_local_ip_btn")
        self.gridLayout.addWidget(self.get_local_ip_btn, 1, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.com_interface_cbb = QtWidgets.QComboBox(self.groupBox)
        self.com_interface_cbb.setObjectName("com_interface_cbb")
        self.com_interface_cbb.addItem("")
        self.com_interface_cbb.addItem("")
        self.gridLayout_2.addWidget(self.com_interface_cbb, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(ORIR_Debug_Page)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_21.setContentsMargins(9, 20, -1, -1)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.runinfo_te = QtWidgets.QTextEdit(self.groupBox_11)
        self.runinfo_te.setObjectName("runinfo_te")
        self.gridLayout_21.addWidget(self.runinfo_te, 1, 0, 1, 4)
        self.cycle_send_period_ms_le = QtWidgets.QLineEdit(self.groupBox_11)
        self.cycle_send_period_ms_le.setObjectName("cycle_send_period_ms_le")
        self.gridLayout_21.addWidget(self.cycle_send_period_ms_le, 4, 0, 1, 1)
        self.clear_runinfo_btn = QtWidgets.QPushButton(self.groupBox_11)
        self.clear_runinfo_btn.setObjectName("clear_runinfo_btn")
        self.gridLayout_21.addWidget(self.clear_runinfo_btn, 2, 3, 1, 1)
        self.send_debug_msg_btn = QtWidgets.QPushButton(self.groupBox_11)
        self.send_debug_msg_btn.setObjectName("send_debug_msg_btn")
        self.gridLayout_21.addWidget(self.send_debug_msg_btn, 4, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_11)
        self.label_14.setObjectName("label_14")
        self.gridLayout_21.addWidget(self.label_14, 0, 0, 1, 1)
        self.send_debug_msg_te = QtWidgets.QTextEdit(self.groupBox_11)
        self.send_debug_msg_te.setObjectName("send_debug_msg_te")
        self.gridLayout_21.addWidget(self.send_debug_msg_te, 3, 0, 1, 4)
        self.label_13 = QtWidgets.QLabel(self.groupBox_11)
        self.label_13.setObjectName("label_13")
        self.gridLayout_21.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_11)
        self.label_15.setObjectName("label_15")
        self.gridLayout_21.addWidget(self.label_15, 4, 1, 1, 1)
        self.send_hex_data_cb = QtWidgets.QCheckBox(self.groupBox_11)
        self.send_hex_data_cb.setChecked(True)
        self.send_hex_data_cb.setObjectName("send_hex_data_cb")
        self.gridLayout_21.addWidget(self.send_hex_data_cb, 4, 2, 1, 1)
        self.is_show_as_hex_cb = QtWidgets.QCheckBox(self.groupBox_11)
        self.is_show_as_hex_cb.setChecked(True)
        self.is_show_as_hex_cb.setObjectName("is_show_as_hex_cb")
        self.gridLayout_21.addWidget(self.is_show_as_hex_cb, 2, 2, 1, 1)
        self.gridLayout_21.setRowStretch(1, 5)
        self.gridLayout_21.setRowStretch(3, 2)
        self.gridLayout_22.addWidget(self.groupBox_11, 0, 2, 8, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(ORIR_Debug_Page)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.walkmotor_pos_le = QtWidgets.QLineEdit(self.groupBox_3)
        self.walkmotor_pos_le.setObjectName("walkmotor_pos_le")
        self.gridLayout_8.addWidget(self.walkmotor_pos_le, 0, 1, 1, 3)
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 2, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 0, 4, 1, 1)
        self.walkmotor_velocity_le = QtWidgets.QLineEdit(self.groupBox_3)
        self.walkmotor_velocity_le.setObjectName("walkmotor_velocity_le")
        self.gridLayout_8.addWidget(self.walkmotor_velocity_le, 1, 1, 1, 3)
        self.walkmotor_set_pos_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.walkmotor_set_pos_btn.setObjectName("walkmotor_set_pos_btn")
        self.gridLayout_8.addWidget(self.walkmotor_set_pos_btn, 0, 0, 1, 1)
        self.walkmotor_set_velocity_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.walkmotor_set_velocity_btn.setObjectName("walkmotor_set_velocity_btn")
        self.gridLayout_8.addWidget(self.walkmotor_set_velocity_btn, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 2, 0, 1, 1)
        self.walkmotor_realtime_speed_le = QtWidgets.QLineEdit(self.groupBox_3)
        self.walkmotor_realtime_speed_le.setObjectName("walkmotor_realtime_speed_le")
        self.gridLayout_8.addWidget(self.walkmotor_realtime_speed_le, 3, 1, 1, 3)
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 3, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 1, 4, 1, 1)
        self.walkmotor_realtime_position_le = QtWidgets.QLineEdit(self.groupBox_3)
        self.walkmotor_realtime_position_le.setObjectName("walkmotor_realtime_position_le")
        self.gridLayout_8.addWidget(self.walkmotor_realtime_position_le, 2, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.walkmotor_backward_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.walkmotor_backward_btn.setObjectName("walkmotor_backward_btn")
        self.gridLayout_7.addWidget(self.walkmotor_backward_btn, 2, 1, 1, 1)
        self.walkmotor_query_velocity_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.walkmotor_query_velocity_btn.setObjectName("walkmotor_query_velocity_btn")
        self.gridLayout_7.addWidget(self.walkmotor_query_velocity_btn, 2, 3, 1, 1)
        self.walkmotor_inplace_le = QtWidgets.QLineEdit(self.groupBox_3)
        self.walkmotor_inplace_le.setObjectName("walkmotor_inplace_le")
        self.gridLayout_7.addWidget(self.walkmotor_inplace_le, 3, 3, 1, 1)
        self.walkmotor_query_pos_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.walkmotor_query_pos_btn.setObjectName("walkmotor_query_pos_btn")
        self.gridLayout_7.addWidget(self.walkmotor_query_pos_btn, 0, 3, 1, 1)
        self.walkmotor_poweroff_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.walkmotor_poweroff_btn.setObjectName("walkmotor_poweroff_btn")
        self.gridLayout_7.addWidget(self.walkmotor_poweroff_btn, 0, 1, 1, 1)
        self.walkmotor_forward_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.walkmotor_forward_btn.setObjectName("walkmotor_forward_btn")
        self.gridLayout_7.addWidget(self.walkmotor_forward_btn, 2, 0, 1, 1)
        self.walkmotor_stop_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.walkmotor_stop_btn.setObjectName("walkmotor_stop_btn")
        self.gridLayout_7.addWidget(self.walkmotor_stop_btn, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 3, 1, 1, 1)
        self.walkmotor_poweron_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.walkmotor_poweron_btn.setObjectName("walkmotor_poweron_btn")
        self.gridLayout_7.addWidget(self.walkmotor_poweron_btn, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_3, 1, 0, 2, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(ORIR_Debug_Page)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_15.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.photoelectricswitch_5_le = QtWidgets.QLineEdit(self.groupBox_6)
        self.photoelectricswitch_5_le.setObjectName("photoelectricswitch_5_le")
        self.gridLayout_14.addWidget(self.photoelectricswitch_5_le, 3, 1, 1, 1)
        self.photoelectricswitch_2_le = QtWidgets.QLineEdit(self.groupBox_6)
        self.photoelectricswitch_2_le.setObjectName("photoelectricswitch_2_le")
        self.gridLayout_14.addWidget(self.photoelectricswitch_2_le, 0, 3, 1, 1)
        self.photoelectricswitch_1_le = QtWidgets.QLineEdit(self.groupBox_6)
        self.photoelectricswitch_1_le.setObjectName("photoelectricswitch_1_le")
        self.gridLayout_14.addWidget(self.photoelectricswitch_1_le, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setObjectName("label_7")
        self.gridLayout_14.addWidget(self.label_7, 2, 0, 1, 1)
        self.photoelectricswitch_6_le = QtWidgets.QLineEdit(self.groupBox_6)
        self.photoelectricswitch_6_le.setObjectName("photoelectricswitch_6_le")
        self.gridLayout_14.addWidget(self.photoelectricswitch_6_le, 3, 3, 1, 1)
        self.photoelectricswitch_3_le = QtWidgets.QLineEdit(self.groupBox_6)
        self.photoelectricswitch_3_le.setObjectName("photoelectricswitch_3_le")
        self.gridLayout_14.addWidget(self.photoelectricswitch_3_le, 2, 1, 1, 1)
        self.photoelectricswitch_4_le = QtWidgets.QLineEdit(self.groupBox_6)
        self.photoelectricswitch_4_le.setObjectName("photoelectricswitch_4_le")
        self.gridLayout_14.addWidget(self.photoelectricswitch_4_le, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setObjectName("label_6")
        self.gridLayout_14.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setObjectName("label_8")
        self.gridLayout_14.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setObjectName("label_9")
        self.gridLayout_14.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        self.label_12.setObjectName("label_12")
        self.gridLayout_14.addWidget(self.label_12, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setObjectName("label_11")
        self.gridLayout_14.addWidget(self.label_11, 3, 2, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_6, 7, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(ORIR_Debug_Page)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_11.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setObjectName("label_27")
        self.gridLayout_10.addWidget(self.label_27, 5, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setObjectName("label_29")
        self.gridLayout_10.addWidget(self.label_29, 6, 2, 1, 1)
        self.lift_pos_le = QtWidgets.QLineEdit(self.groupBox_4)
        self.lift_pos_le.setObjectName("lift_pos_le")
        self.gridLayout_10.addWidget(self.lift_pos_le, 3, 1, 1, 1)
        self.lift_velocity_le = QtWidgets.QLineEdit(self.groupBox_4)
        self.lift_velocity_le.setObjectName("lift_velocity_le")
        self.gridLayout_10.addWidget(self.lift_velocity_le, 4, 1, 1, 1)
        self.lift_stop_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.lift_stop_btn.setObjectName("lift_stop_btn")
        self.gridLayout_10.addWidget(self.lift_stop_btn, 2, 0, 1, 1)
        self.lift_up_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.lift_up_btn.setObjectName("lift_up_btn")
        self.gridLayout_10.addWidget(self.lift_up_btn, 1, 0, 1, 1)
        self.lift_inplace_le = QtWidgets.QLineEdit(self.groupBox_4)
        self.lift_inplace_le.setObjectName("lift_inplace_le")
        self.gridLayout_10.addWidget(self.lift_inplace_le, 2, 2, 1, 1)
        self.lift_realtime_pos_le = QtWidgets.QLineEdit(self.groupBox_4)
        self.lift_realtime_pos_le.setObjectName("lift_realtime_pos_le")
        self.gridLayout_10.addWidget(self.lift_realtime_pos_le, 5, 1, 1, 1)
        self.lift_poweroff_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.lift_poweroff_btn.setObjectName("lift_poweroff_btn")
        self.gridLayout_10.addWidget(self.lift_poweroff_btn, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_10.addWidget(self.label_24, 3, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_10.addWidget(self.label_25, 4, 2, 1, 1)
        self.lift_query_velocity_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.lift_query_velocity_btn.setObjectName("lift_query_velocity_btn")
        self.gridLayout_10.addWidget(self.lift_query_velocity_btn, 1, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setObjectName("label_23")
        self.gridLayout_10.addWidget(self.label_23, 2, 1, 1, 1)
        self.lift_set_pos_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.lift_set_pos_btn.setObjectName("lift_set_pos_btn")
        self.gridLayout_10.addWidget(self.lift_set_pos_btn, 3, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setObjectName("label_28")
        self.gridLayout_10.addWidget(self.label_28, 6, 0, 1, 1)
        self.lift_query_pos_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.lift_query_pos_btn.setObjectName("lift_query_pos_btn")
        self.gridLayout_10.addWidget(self.lift_query_pos_btn, 0, 2, 1, 1)
        self.lift_realtime_speed_le = QtWidgets.QLineEdit(self.groupBox_4)
        self.lift_realtime_speed_le.setObjectName("lift_realtime_speed_le")
        self.gridLayout_10.addWidget(self.lift_realtime_speed_le, 6, 1, 1, 1)
        self.lift_set_velocity_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.lift_set_velocity_btn.setObjectName("lift_set_velocity_btn")
        self.gridLayout_10.addWidget(self.lift_set_velocity_btn, 4, 0, 1, 1)
        self.lift_poweron_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.lift_poweron_btn.setObjectName("lift_poweron_btn")
        self.gridLayout_10.addWidget(self.lift_poweron_btn, 0, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 5, 0, 1, 1)
        self.lift_down_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.lift_down_btn.setObjectName("lift_down_btn")
        self.gridLayout_10.addWidget(self.lift_down_btn, 1, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_4, 3, 0, 3, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(ORIR_Debug_Page)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_16.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.hall_query_position_btn = QtWidgets.QPushButton(self.groupBox_7)
        self.hall_query_position_btn.setObjectName("hall_query_position_btn")
        self.horizontalLayout_4.addWidget(self.hall_query_position_btn)
        self.hall_position_le = QtWidgets.QLineEdit(self.groupBox_7)
        self.hall_position_le.setObjectName("hall_position_le")
        self.horizontalLayout_4.addWidget(self.hall_position_le)
        self.gridLayout_16.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ranging_query_position_btn = QtWidgets.QPushButton(self.groupBox_7)
        self.ranging_query_position_btn.setObjectName("ranging_query_position_btn")
        self.horizontalLayout_5.addWidget(self.ranging_query_position_btn)
        self.ranging_cur_position_le = QtWidgets.QLineEdit(self.groupBox_7)
        self.ranging_cur_position_le.setObjectName("ranging_cur_position_le")
        self.horizontalLayout_5.addWidget(self.ranging_cur_position_le)
        self.gridLayout_16.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.barcode_query_position_btn = QtWidgets.QPushButton(self.groupBox_7)
        self.barcode_query_position_btn.setObjectName("barcode_query_position_btn")
        self.horizontalLayout_3.addWidget(self.barcode_query_position_btn)
        self.barcode_position_le = QtWidgets.QLineEdit(self.groupBox_7)
        self.barcode_position_le.setObjectName("barcode_position_le")
        self.horizontalLayout_3.addWidget(self.barcode_position_le)
        self.gridLayout_16.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_7, 6, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(ORIR_Debug_Page)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.pd_query_UHF_TEV_PRPD_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.pd_query_UHF_TEV_PRPD_btn.setObjectName("pd_query_UHF_TEV_PRPD_btn")
        self.gridLayout_17.addWidget(self.pd_query_UHF_TEV_PRPD_btn, 10, 1, 1, 1)
        self.pd_selfcheck_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.pd_selfcheck_btn.setObjectName("pd_selfcheck_btn")
        self.gridLayout_17.addWidget(self.pd_selfcheck_btn, 1, 2, 1, 1)
        self.pd_motor_inplace_le = QtWidgets.QLineEdit(self.groupBox_8)
        self.pd_motor_inplace_le.setObjectName("pd_motor_inplace_le")
        self.gridLayout_17.addWidget(self.pd_motor_inplace_le, 8, 1, 1, 1)
        self.pd_motor_drawback_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.pd_motor_drawback_btn.setObjectName("pd_motor_drawback_btn")
        self.gridLayout_17.addWidget(self.pd_motor_drawback_btn, 3, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_8)
        self.label_34.setObjectName("label_34")
        self.gridLayout_17.addWidget(self.label_34, 4, 1, 1, 1)
        self.pd_poweron_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.pd_poweron_btn.setObjectName("pd_poweron_btn")
        self.gridLayout_17.addWidget(self.pd_poweron_btn, 1, 0, 1, 1)
        self.pd_query_ultrasonic_PRPD_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.pd_query_ultrasonic_PRPD_btn.setObjectName("pd_query_ultrasonic_PRPD_btn")
        self.gridLayout_17.addWidget(self.pd_query_ultrasonic_PRPD_btn, 9, 1, 1, 1)
        self.pd_motor_set_pos_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.pd_motor_set_pos_btn.setObjectName("pd_motor_set_pos_btn")
        self.gridLayout_17.addWidget(self.pd_motor_set_pos_btn, 6, 0, 1, 1)
        self.pd_query_UHF_TEV_value_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.pd_query_UHF_TEV_value_btn.setObjectName("pd_query_UHF_TEV_value_btn")
        self.gridLayout_17.addWidget(self.pd_query_UHF_TEV_value_btn, 10, 0, 1, 1)
        self.pd_result_le = QtWidgets.QLineEdit(self.groupBox_8)
        self.pd_result_le.setObjectName("pd_result_le")
        self.gridLayout_17.addWidget(self.pd_result_le, 0, 1, 1, 2)
        self.pd_motor_set_pos_le = QtWidgets.QLineEdit(self.groupBox_8)
        self.pd_motor_set_pos_le.setObjectName("pd_motor_set_pos_le")
        self.gridLayout_17.addWidget(self.pd_motor_set_pos_le, 6, 1, 1, 1)
        self.pd_query_ultrasonic_PRPS_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.pd_query_ultrasonic_PRPS_btn.setObjectName("pd_query_ultrasonic_PRPS_btn")
        self.gridLayout_17.addWidget(self.pd_query_ultrasonic_PRPS_btn, 9, 2, 1, 1)
        self.pd_motor_stretch_out_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.pd_motor_stretch_out_btn.setObjectName("pd_motor_stretch_out_btn")
        self.gridLayout_17.addWidget(self.pd_motor_stretch_out_btn, 3, 0, 1, 1)
        self.pd_poweroff_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.pd_poweroff_btn.setObjectName("pd_poweroff_btn")
        self.gridLayout_17.addWidget(self.pd_poweroff_btn, 1, 1, 1, 1)
        self.pd_detect_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.pd_detect_btn.setObjectName("pd_detect_btn")
        self.gridLayout_17.addWidget(self.pd_detect_btn, 0, 0, 1, 1)
        self.pd_motor_query_pos_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.pd_motor_query_pos_btn.setObjectName("pd_motor_query_pos_btn")
        self.gridLayout_17.addWidget(self.pd_motor_query_pos_btn, 4, 0, 1, 1)
        self.pd_query_UHF_TEV_PRPS_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.pd_query_UHF_TEV_PRPS_btn.setObjectName("pd_query_UHF_TEV_PRPS_btn")
        self.gridLayout_17.addWidget(self.pd_query_UHF_TEV_PRPS_btn, 10, 2, 1, 1)
        self.pd_query_ultrasonic_value_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.pd_query_ultrasonic_value_btn.setObjectName("pd_query_ultrasonic_value_btn")
        self.gridLayout_17.addWidget(self.pd_query_ultrasonic_value_btn, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_8)
        self.label_3.setObjectName("label_3")
        self.gridLayout_17.addWidget(self.label_3, 8, 0, 1, 1)
        self.pd_motor_pos_le = QtWidgets.QLineEdit(self.groupBox_8)
        self.pd_motor_pos_le.setObjectName("pd_motor_pos_le")
        self.gridLayout_17.addWidget(self.pd_motor_pos_le, 4, 2, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_8, 4, 1, 3, 1)
        self.gridLayout_22.setColumnStretch(0, 1)
        self.gridLayout_22.setColumnStretch(1, 1)
        self.gridLayout_22.setColumnStretch(2, 20)
        self.gridLayout_23.addLayout(self.gridLayout_22, 0, 0, 1, 1)

        self.retranslateUi(ORIR_Debug_Page)
        self.net_type_cbb.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ORIR_Debug_Page)

    def retranslateUi(self, ORIR_Debug_Page):
        ORIR_Debug_Page.setWindowTitle(QtWidgets.QApplication.translate("ORIR_Debug_Page", "Form", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("ORIR_Debug_Page", "状态灯", None, -1))
        self.statuslight_red_on_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "红灯亮", None, -1))
        self.statuslight_yellow_on_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "黄灯亮", None, -1))
        self.statuslight_green_on_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "绿灯亮", None, -1))
        self.statuslight_all_off_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "灭", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("ORIR_Debug_Page", "云台", None, -1))
        self.ptz_stop_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "停", None, -1))
        self.ptz_irup_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "右上", None, -1))
        self.ptz_irdown_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "右下", None, -1))
        self.ptz_vldown_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "左下", None, -1))
        self.ptz_vlup_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "左上", None, -1))
        self.ptz_right_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "右", None, -1))
        self.ptz_left_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "左", None, -1))
        self.ptz_query_left_tilt_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "查询左俯仰", None, -1))
        self.ptz_query_right_tilt_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "查询右俯仰", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "度", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "度", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "度", None, -1))
        self.ptz_set_left_tilt_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "设置左俯仰", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "度", None, -1))
        self.ptz_cur_pan_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.00", None, -1))
        self.ptz_query_bearing_pitching_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "同时查询", None, -1))
        self.ptz_query_bearing_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "查询方位", None, -1))
        self.ptz_set_bearing_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "设置方位", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "度", None, -1))
        self.ptz_set_right_tilt_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "设置右俯仰", None, -1))
        self.ptz_bearing_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.00", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "度", None, -1))
        self.ptz_set_bearing_pitching_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "同时设置", None, -1))
        self.ptz_set_left_tilt_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.00", None, -1))
        self.ptz_cur_left_tilt_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.00", None, -1))
        self.ptz_set_right_tilt_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.00", None, -1))
        self.ptz_cur_right_tilt_le_.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.00", None, -1))
        self.ptz_pitching_le_9.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.00", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "度/秒", None, -1))
        self.ptz_self_check_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "云台自检", None, -1))
        self.ptz_cur_velocity_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.5", None, -1))
        self.ptz_poweroff_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "下电", None, -1))
        self.ptz_query_velocity_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "速度查询", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "度/秒", None, -1))
        self.ptz_set_velocity_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.5", None, -1))
        self.ptz_poweron_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "上电", None, -1))
        self.ptz_set_velocity_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "设置速度", None, -1))
        self.ptz_set_zero_position_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "云台校正", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "到位反馈", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("ORIR_Debug_Page", "设置", None, -1))
        self.net_type_cbb.setItemText(0, QtWidgets.QApplication.translate("ORIR_Debug_Page", "TCP服务器", None, -1))
        self.net_type_cbb.setItemText(1, QtWidgets.QApplication.translate("ORIR_Debug_Page", "TCP客户端", None, -1))
        self.net_type_cbb.setItemText(2, QtWidgets.QApplication.translate("ORIR_Debug_Page", "UDP服务器", None, -1))
        self.net_type_cbb.setItemText(3, QtWidgets.QApplication.translate("ORIR_Debug_Page", "UDP客户端", None, -1))
        self.port_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "8800", None, -1))
        self.ip_addr_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "192.168.1.30", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "  端  口", None, -1))
        self.net_connect_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "连接", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "  IP地址", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "网络类型", None, -1))
        self.get_local_ip_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "获取本机IP", None, -1))
        self.com_interface_cbb.setItemText(0, QtWidgets.QApplication.translate("ORIR_Debug_Page", "GRPC 接口", None, -1))
        self.com_interface_cbb.setItemText(1, QtWidgets.QApplication.translate("ORIR_Debug_Page", "通信协议接口", None, -1))
        self.groupBox_11.setTitle(QtWidgets.QApplication.translate("ORIR_Debug_Page", "调试框", None, -1))
        self.cycle_send_period_ms_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0", None, -1))
        self.clear_runinfo_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "清除", None, -1))
        self.send_debug_msg_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "发送", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "接收框", None, -1))
        self.send_debug_msg_te.setHtml(QtWidgets.QApplication.translate("ORIR_Debug_Page", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">12345</span></p></body></html>", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "发送框", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "ms", None, -1))
        self.send_hex_data_cb.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "十六进制发送", None, -1))
        self.is_show_as_hex_cb.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "十六进制显示", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("ORIR_Debug_Page", "行走电机", None, -1))
        self.walkmotor_pos_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.0", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "mm", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "mm", None, -1))
        self.walkmotor_velocity_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "100", None, -1))
        self.walkmotor_set_pos_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "设置位置", None, -1))
        self.walkmotor_set_velocity_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "设置速度", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "   速度:", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "   位置:", None, -1))
        self.walkmotor_realtime_speed_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.0", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "mm/s", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "mm/s", None, -1))
        self.walkmotor_realtime_position_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.0", None, -1))
        self.walkmotor_backward_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "后退", None, -1))
        self.walkmotor_query_velocity_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "速度查询", None, -1))
        self.walkmotor_inplace_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.0", None, -1))
        self.walkmotor_query_pos_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "查询位置", None, -1))
        self.walkmotor_poweroff_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "下电", None, -1))
        self.walkmotor_forward_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "前进", None, -1))
        self.walkmotor_stop_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "停", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "    到位", None, -1))
        self.walkmotor_poweron_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "上电", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("ORIR_Debug_Page", "光电开关", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "  开关3：", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "  开关1：", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "  开关5：", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "  开关2：", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "  开关4：", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "  开关6：", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("ORIR_Debug_Page", "升降杆", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "mm", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "mm/s", None, -1))
        self.lift_pos_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.0", None, -1))
        self.lift_velocity_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "100", None, -1))
        self.lift_stop_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "停", None, -1))
        self.lift_up_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "升", None, -1))
        self.lift_inplace_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.0", None, -1))
        self.lift_realtime_pos_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.0", None, -1))
        self.lift_poweroff_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "下电", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "mm", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "mm/s", None, -1))
        self.lift_query_velocity_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "速度查询", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "    到位", None, -1))
        self.lift_set_pos_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "设置位置", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "   速度:", None, -1))
        self.lift_query_pos_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "查询位置", None, -1))
        self.lift_realtime_speed_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.0", None, -1))
        self.lift_set_velocity_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "设置速度", None, -1))
        self.lift_poweron_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "上电", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "   位置:", None, -1))
        self.lift_down_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "降", None, -1))
        self.groupBox_7.setTitle(QtWidgets.QApplication.translate("ORIR_Debug_Page", "局放", None, -1))
        self.hall_query_position_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "霍尔信息", None, -1))
        self.ranging_query_position_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "测距位置", None, -1))
        self.barcode_query_position_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "条码信息", None, -1))
        self.groupBox_8.setTitle(QtWidgets.QApplication.translate("ORIR_Debug_Page", "局放控制", None, -1))
        self.pd_query_UHF_TEV_PRPD_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "UHF/TEV PRPD", None, -1))
        self.pd_selfcheck_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "自检", None, -1))
        self.pd_motor_drawback_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "缩", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "   位置:", None, -1))
        self.pd_poweron_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "上电", None, -1))
        self.pd_query_ultrasonic_PRPD_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "超声波PRPD", None, -1))
        self.pd_motor_set_pos_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "设置位置", None, -1))
        self.pd_query_UHF_TEV_value_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "UHF/TEV值", None, -1))
        self.pd_motor_set_pos_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.0", None, -1))
        self.pd_query_ultrasonic_PRPS_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "超声波PRPS", None, -1))
        self.pd_motor_stretch_out_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "伸", None, -1))
        self.pd_poweroff_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "下电", None, -1))
        self.pd_detect_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "局放信息", None, -1))
        self.pd_motor_query_pos_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "查询位置", None, -1))
        self.pd_query_UHF_TEV_PRPS_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "UHF/TEV PRPS", None, -1))
        self.pd_query_ultrasonic_value_btn.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "超声波值", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "到位反馈", None, -1))
        self.pd_motor_pos_le.setText(QtWidgets.QApplication.translate("ORIR_Debug_Page", "0.0", None, -1))

